NumberOfVars = 19;
InitialPopFunction = @PopFunction;
gaOptions = gaoptimset('CreationFcn', {InitialPopFunction},...
                       'PopulationSize',50,...
                     'Generations',50,...
                     'PopulationType', 'bitstring',...
                     'SelectionFcn',{@selectionroulette},...
                     'MutationFcn',{@mutationuniform, 0.1},...
                     'CrossoverFcn', {@crossoversinglepoint},...
                     'EliteCount',2,...
                     'StallGenLimit',100,...
                     'PlotFcns',{@gaplotbestf, @gaplotbestindiv, @gaplotexpectation, @gaplotgenealogy},...  
                     'UseParallel', true,...
                     'Vectorized', 'off',...
                     'Display', 'iter'); 
                 
FitnessFunction = @MCI_Conversion_FitnessRusBoost;
[chromosome,fval,exitflag,output,population,scores]=ga(FitnessFunction, NumberOfVars, gaOptions);
bestFeatures = find(chromosome==1);
